# This file was generated by running "update-rt-siteconfig-4".
#
# While local modifications will not be overwritten without permission,
# it is recommended the they are instead placed in 
# /etc/request-tracker4/RT_SiteConfig.d
#
# Note that modifications to the RT_SiteConfig.d directory won't 
# take effect until the update command mentioned above is run again.

# start /etc/request-tracker4/RT_SiteConfig.d/40-timezone
# dynamically find out the current timezone
my $zone = "UTC";
$zone=`/bin/cat /etc/timezone`
    if -f "/etc/timezone";
chomp $zone;
Set($Timezone, $zone);
# end   /etc/request-tracker4/RT_SiteConfig.d/40-timezone
# start /etc/request-tracker4/RT_SiteConfig.d/50-debconf
# THE BASICS:

Set($rtname, 'rt.tkldev');
Set($Organization, 'tkldev');

Set($CorrespondAddress , 'rt@tkldev');
Set($CommentAddress , 'rt-comment@tkldev');

# THE WEBSERVER:

Set($WebPath , "/rt");
Set($WebBaseURL , "http://localhost");
Set($WebPort, 80);

# end   /etc/request-tracker4/RT_SiteConfig.d/50-debconf
# start /etc/request-tracker4/RT_SiteConfig.d/51-dbconfig-common
# THE DATABASE:
# generated by dbconfig-common

Set($DatabaseType, 'Pg');
Set($DatabaseHost, 'localhost');
Set($DatabasePort, '');

Set($DatabaseName , 'rt_db');

Set($DatabaseUser , 'rt_user');
Set($DatabasePassword , 'password'); 

# TODO: Need to set this to the root account?
# Maybe hook into the Pg setup script and barrow
# the temp root password, just need to make sure it's 
# changed on startup

Set ($DatabaseAdmin , 'rt_user'); 
# end   /etc/request-tracker4/RT_SiteConfig.d/51-dbconfig-common
# start /etc/request-tracker4/RT_SiteConfig.d/60-email-settings

Set($SMTPServer, "localhost");

Set($SMTPFrom, "rt@localhost");
# end   /etc/request-tracker4/RT_SiteConfig.d/60-email-settings
# start /etc/request-tracker4/RT_SiteConfig.d/60-logging
# Logging to file isn't a good default strategy; see #747076
Set($LogToFile , undef);
Set($LogDir, '/var/log/request-tracker4');
Set($LogToFileNamed , "rt.log");    #log to rt.log

# Log to Syslog by default instead
Set($LogToSyslog, 'warning');
# end   /etc/request-tracker4/RT_SiteConfig.d/60-logging
1;
