# This file was generated by running "update-rt-siteconfig".
#
# While local modifications will not be overwritten without permission,
# it is recommended the they are instead placed in 
# /etc/request-tracker4/RT_SiteConfig.d
#
# Note that modifications to the RT_SiteConfig.d directory won't 
# take effect until the update command mentioned above is run again.

# start /etc/request-tracker4/RT_SiteConfig.d/40-timezone
# dynamically find out the current timezone
my $zone = "UTC";
$zone=`/bin/cat /etc/timezone`
    if -f "/etc/timezone";
chomp $zone;
Set($Timezone, $zone);
# end   /etc/request-tracker4/RT_SiteConfig.d/40-timezone
# start /etc/request-tracker4/RT_SiteConfig.d/50-debconf
# THE BASICS:

Set($rtname, 'rt.tkldev');
Set($Organization, 'tkldev');

Set($CorrespondAddress , 'rt@tkldev');
Set($CommentAddress , 'rt-comment@tkldev');

# THE WEBSERVER:

Set($WebPath , "/rt");
Set($WebBaseURL , "http://localhost");
Set($WebPort, 80);

# end   /etc/request-tracker4/RT_SiteConfig.d/50-debconf
# start /etc/request-tracker4/RT_SiteConfig.d/51-dbconfig-common
# THE DATABASE:
# generated by dbconfig-common

# map from dbconfig-common database types to their names as known by RT
my %typemap = (
    mysql   => 'mysql',
    pgsql   => 'Pg',
    sqlite3 => 'SQLite',
);
    
Set($DatabaseType, $typemap{pgsql} || "UNKNOWN");

Set($DatabaseHost, 'localhost');
Set($DatabasePort, '');

Set($DatabaseName , 'rt_db');

Set($DatabaseUser , 'rt_user');
Set($DatabasePassword , 'password');

# end   /etc/request-tracker4/RT_SiteConfig.d/51-dbconfig-common
1;
