#!/bin/bash -ex
# required environment variables: CODENAME

#
# Code used from TurnKey Linux
# https://raw.githubusercontent.com/turnkeylinux-apps/canvas/master/conf.d/00backports
#
# Installs backport packages for RT 4.0
#

fatal() {
    echo "[$(basename $0)] fatal: $@" 1>&2
    exit 1
}

NAME="wheezy-backports"
PACKAGES="libhtml-rewriteattributes-perl rt4-clients rt4-apache2 rt4-db-postgresql request-tracker4"

[ "$CODENAME" == "wheezy" ] || fatal "CODENAME is not wheezy"

cat >/etc/apt/sources.list.d/$NAME.list<<EOF
deb http://cdn.debian.net/debian $NAME main
EOF

cat >/etc/apt/preferences.d/$NAME<<EOF
Package: *
Pin: release a=$NAME
Pin-Priority: 100

Package: $PACKAGES
Pin: release a=$NAME
Pin-Priority: 500
EOF

apt-get update
DEBIAN_FRONTEND=noninteractive apt-get --force-yes --assume-yes install $PACKAGES
