#!/bin/bash -ex

# TODO: randomize the password  
# 


# Create the rt database user and database

# Start database server
service postgresql start


# add rt user
psql <<EOF
\x
CREATE ROLE "rt_user" CREATEDB LOGIN PASSWORD 'password' CREATEROLE;
EOF

# Create the database
rt-setup-database --action init --dba-password 'password'  

# Stop the database
service postgresql stop
