#!/bin/sh -ex

DB_USER=rtuser
DB_PASS=$(mcookie)

a2dissite 000-default.conf
a2ensite rt4

# Start database server
service postgresql start

# add rtuser
psql <<EOF
\x
CREATE ROLE "%DB_USER" CREATEDB LOGIN PASSWORD "$DB_PASS" CREATEROLE;
EOF

#Create the database
rt-setup-database --action init --dba-password "$DB_PASS"

# Stop the database
service postgresql stop
