#!/bin/bash -e
# regenerate rt secrets and postgresql password

. /etc/default/inithooks

CONF=
sed -i "s|'generatepasswordtmpl.*|'generatepasswordtmpl' => '$(uuidgen)',|" $CONF
sed -i "s|'lostpasswordtmpl.*|'lostpasswordtmpl' => '$(uuidgen)',|" $CONF
sed -i "s|'unique_key.*|'unique_key' => '$(mcookie)',|" $CONF

PASSWORD=$(mcookie)
sed -i "s|dbpass.*|dbpass = '$PASSWORD';|" $CONF
$INITHOOKS_PATH/bin/pgsqlconf.py --user=rt_usr --pass="$PASSWORD"
